apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: yoyox2003/bm-grad_api:latest
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: "database-service"   
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: MYSQL_DATABASE
---
apiVersion: v1  
kind: Service
metadata:   
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 5001
    targetPort: 5001 

