apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: app  
  template:
    metadata:
      labels:
        app: app  
    spec: 
      containers:
      - name: app
        image:  yoyox2003/bm-grad-app:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - port: 5002
    targetPort: 5002