apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
data:
  MYSQL_DATABASE: cXVvdGVzZGI=
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  # The above values are base64 encoded.